### ISSUE TITLE
Creating a document with an empty content returns an error.

### ISSUE THREAD

**Issue by chc5** [chc5/gitgud#17]
/api/docs/create with {content: ""} returns an error on the backend

**Comment by melvinheks** [comment]
true

**Comment by melvinheks** [comment]
Fixed in PR #18

**Comment by chc5** [comment]
![image](https://user-images.githubusercontent.com/21010314/48924390-77a28200-ee85-11e8-8b0d-f93b4b7c9a6a.png)
Content is undefined when it should return an empty string.

**Comment by chc5** [comment]
This issue only occurs when i only send `{title: docName }` as my body of the POST request. The method still works when I send `{title: docName, content:""}`

**Comment by melvinheks** [comment]
Fixed in PR #19
